name: Markdown Linting

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v4

      - name: 2. Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 3. Install dependencies
        run: npm ci

      - name: 4. Install cspell
        run: npm install -g cspell

      - name: 5. Run Markdown lint
        run: npm run lint:md

      - name: 6. Run Spell Check
        run: cspell "**/*.md" --no-progress --color